### ISSUE TITLE
Custom gen issues

### ISSUE THREAD

**Issue by robertplayscz** [nullworks/accgen-web#59] opened 2019-05-30 20:42 UTC
hello, i just became a patron and it still says that im not a patron yet.
my patron profile is: https://www.patreon.com/patreonuser987
Please help me.
screen: https://imgur.com/a/Y0ruMk1

**Comment by BenCat07** [comment] 2019-05-30 21:19
Could you please send us your Patreon User ID?

**Comment by TotallyNotElite** [comment] 2019-05-30 21:22
Hello! We're having some issues with the patreon api for some reason. It doesn't actually add you to the patreon api list. We're looking into the issue right now.

**Comment by robertplayscz** [comment] 2019-05-30 21:24
@BenCat07 where to grab my user id? I gave u the link.

**Comment by TotallyNotElite** [comment] 2019-05-30 23:13
@robertplayscz Can you check if it works now?

**Comment by robertplayscz** [comment] 2019-05-31 04:10
@TotallyNotElite yes, it works but it takes ages to get my account.

**Comment by robertplayscz** [comment] 2019-05-31 04:15
@TotallyNotElite when im trying to make new account, it gives me this error. https://imgur.com/a/Rl7tv16

**Comment by Ashesh3** [comment] 2019-05-31 06:08
"dasdasg"

**Comment by TotallyNotElite** [comment] 2019-05-31 10:09
@robertplayscz Hello! We've added a redundant server that should catch any lingering tasks that may not get picked up by our main servers. Can you try again and close the issue if it's fixed?

**Comment by robertplayscz** [comment] 2019-05-31 11:05
@TotallyNotElite nope. I am still getting the same error. :/

**Comment by TotallyNotElite** [comment] 2019-05-31 11:15
> @TotallyNotElite nope. I am still getting the same error. :/

Wtf?? Can you send the profile picture that you want to use here? That's the only thing I can think of right now.

**Comment by robertplayscz** [comment] 2019-05-31 11:18
Yes.
https://i.imgur.com/a/ETAQ68S

**Comment by TotallyNotElite** [comment] 2019-05-31 11:32
Custom gen doesn't time out for me:
![custom_gen_demo](https://user-images.githubusercontent.com/38938720/58703248-4fea2480-83a8-11e9-8e4a-d9a610453ea8.gif)

**Comment by TotallyNotElite** [comment] 2019-05-31 11:34
Yes the image seems to be the problem

**Comment by robertplayscz** [comment] 2019-05-31 12:18
so how do i enter the image? :/

**Comment by robertplayscz** [comment] 2019-05-31 12:21
Yeah, it works for me now. But im still sad that i cant enter the image :D

**Comment by TotallyNotElite** [comment] 2019-05-31 15:24
Hello! The issue is that your image is an album, not a direct link to the image.

**Closed by TotallyNotElite** 2019-05-31 15:24 UTC

**Comment by TotallyNotElite** [comment] 2019-05-31 15:34
The direct link would be https://i.imgur.com/GOBJdk4.jpg.
